import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppProvider } from '@/Context/AppContext';
import './globals.css';
import './style.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Facebook – log in or sign up',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
        {children}
        </AppProvider>
        </body>
    </html>
  );
}
