export const data = [
  {
    id: 1,
    name: 'Neil Sims',
    position: 'React Developer',
    email: 'neil.sims@flowbite.com',
    status: 'Online',
    phone: '130-309-6439',
  },
  {
    id: 2,
    name: 'Bonnie Green',
    position: 'Designer',
    email: 'bonnie@flowbite.com',
    status: 'Online',
    phone: '130-309-6559',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    position: 'Frontend Developer',
    email: 'alice.johnson@example.com',
    status: 'Online',
    phone: '130-309-6777',
  },
  {
    id: 4,
    name: 'Michael Smith',
    position: 'Backend Developer',
    email: 'michael.smith@example.com',
    status: 'Offline',
    phone: '130-309-6888',
  },
  {
    id: 5,
    name: 'Emma White',
    position: 'UI/UX Designer',
    email: 'emma.white@example.com',
    status: 'Online',
    phone: '130-309-6999',
  },
  {
    id: 6,
    name: 'David Brown',
    position: 'Software Engineer',
    email: 'david.brown@example.com',
    status: 'Online',
    phone: '130-309-7111',
  },
  {
    id: 7,
    name: 'Sarah Clark',
    position: 'Product Manager',
    email: 'sarah.clark@example.com',
    status: 'Online',
    phone: '130-309-7222',
  },
  {
    id: 8,
    name: 'James Wilson',
    position: 'Quality Assurance',
    email: 'james.wilson@example.com',
    status: 'Offline',
    phone: '130-309-7333',
  },
  {
    id: 9,
    name: 'Olivia Taylor',
    position: 'Marketing Specialist',
    email: 'olivia.taylor@example.com',
    status: 'Online',
    phone: '130-309-7444',
  },
  {
    id: 10,
    name: 'Daniel Anderson',
    position: 'Data Analyst',
    email: 'daniel.anderson@example.com',
    status: 'Offline',
    phone: '130-309-7555',
  },
  {
    id: 11,
    name: 'Sophia Martinez',
    position: 'Content Writer',
    email: 'sophia.martinez@example.com',
    status: 'Online',
    phone: '130-309-7666',
  }
];
